version: '3'
services:
  web:
    image: aionicos/client-dev
    volumes:
      - /app/node_modules
      - ./client:/app
    command: npm run dev
  api: 
    image: aionicos/api-dev
    environment:
      - GITHUB_ID=
      - GITHUB_SECRET=
      - GITHUB_CALLBACK_URL=
      - url=h
      - api_key=
      - mongodb_uri=

    command: npm run dev
    volumes:
     - /app/node_modules
     - ./server/dist:/app/dist
     - ./server/AppConfig.json:/app/App.Config.json
  nginx:
    depends_on:
      - web
      - api
    image: aionicos/nginx
    ports:
      - "2500:80"

