version: '3.9'
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    command: npm run dev
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - GITHUB_ID=4989bb59352a0a0db020
      - GITHUB_SECRET=fdc45f02d69977612270cb1b9f48c4c9b7b3582d
      - GITHUB_CALLBACK_URL=http://localhost:3000/server/auth/github/callback
      - url=https://host.docker.internal:8080
      - api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJuYXRoYW46YXBpS2V5IiwibmJmIjoxNjg2MDk5MTQ2LCJpYXQiOjE2ODYwOTkxNDYsImp0aSI6IjBkNTFiYmM2LWRlMjktNGExNS05YTVhLThjMjYzODk4MGQzZiJ9.WgcIXZhH7L3TEE4kXYdwDAsPBqLFVoZRl6NBc8dPTG0
      - mongodb_uri=mongodb+srv://nathanmlui:SecurePassword1900@cluster0.jbbgs.azure.mongodb.net/?retryWrites=true&w=majority
  nginx:
    depends_on:
      - web
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
