version: '3.9'
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    command: npm run dev
  api: 
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - GITHUB_ID=2c6ec986c48095990a1c
      - GITHUB_SECRET=8c5d43ec38179de6264f661317b7c0f56a196050
      - GITHUB_CALLBACK_URL=https://localhost:2500/server/auth/github/callback
      - url=https://host.docker.internal:1995
      - api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJ0aW1vdGh5OmFwaUtleSIsIm5iZiI6MTY3NzY4ODI4NSwiaWF0IjoxNjc3Njg4Mjg1LCJqdGkiOiIzZDA0YmE2OS1kOTc1LTQzNTgtYjNjMS05MzQzZWYxZDQ3ZjgifQ.87DLheXEYF8D3mpDb3QsilNsQ11MARNzY6qeFPYDvdU
      - mongodb_uri=mongodb+srv://timothy:GqaPQRkAs298yaY1@cluster0.axjjrae.mongodb.net/?retryWrites=true&w=majority
      - PORT=3000
  nginx:
    depends_on:
      - web
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "2500:80"