version: '3.9'
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    command: npm run dev
  api: 
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
       - GITHUB_ID=
      - GITHUB_SECRET=
      - url=
      - api_key=
      - mongodb_uri=
      - PORT=
    command: npm run dev
  nginx:
    depends_on:
      - web
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"