version: '3'
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    # ports:
    #   - '5173:5173'
    command: npm run dev
  api: 
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    # volumes:
    #  - /app/node_modules
    #  - ./server/dist:/app/dist
    #  - ./server/AppConfig.json:/app/App.Config.json
    # ports:
    #   - '3000:3000'
  nginx:
    depends_on:
      - web
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
